// data.jsx — Spot.it content model (realistic FR data, ready for RN handoff)
// Exposes: CATEGORIES, OFFERS (window globals)

// Warm category palette — editorial, never Google-blue.
const CATEGORIES = {
  mode:   { id: 'mode',   label: 'Mode',   hue: '#C75B43', tint: '#F6E4DD' },
  tech:   { id: 'tech',   label: 'Tech',   hue: '#3B342C', tint: '#EAE4DB' },
  maison: { id: 'maison', label: 'Maison', hue: '#A9794E', tint: '#F1E7D8' },
  beaute: { id: 'beaute', label: 'Beauté', hue: '#B26B7A', tint: '#F4E5E9' },
};

// Each offer carries everything a card / detail / map pin needs.
// grad = duotone "photo" placeholder (dev swaps for a real product image).
// x / y = normalised position on the custom map (0..1).
const OFFERS = [
  {
    id: 'sandro',
    brand: 'Sandro',
    category: 'mode',
    offer: '-20% sur la nouvelle collection',
    teaser: 'Nouvelle collection',
    distance: 280, distanceLabel: '280 m', walk: 4,
    why: 'Parce que tu adores la mode — et c’est à 4 min à pied.',
    sponsored: false,
    grad: ['#2C2622', '#6E625A'], ink: '#FBF7F2',
    wordmark: { text: 'SANDRO', spacing: 6, weight: 500, italic: false },
    x: 0.34, y: 0.42,
    address: '50 rue de Rennes, 75006',
    desc: 'La nouvelle collection Sandro arrive en boutique. Pièces tailleur, mailles fines et coupes nettes — l’offre est valable sur l’ensemble du nouvel arrivage.',
  },
  {
    id: 'sephora',
    brand: 'Sephora',
    category: 'beaute',
    offer: 'Ton cadeau dès 75€ d’achat',
    teaser: 'Cadeau offert',
    distance: 150, distanceLabel: '150 m', walk: 2,
    why: 'Tu explores la beauté en ce moment — et c’est juste au coin.',
    sponsored: true,
    grad: ['#211A18', '#9E3B2E'], ink: '#FCEDE8',
    wordmark: { text: 'SEPHORA', spacing: 3, weight: 600, italic: false },
    x: 0.58, y: 0.3,
    address: '66 av. des Champs, 75008',
    desc: 'Un cadeau beauté exclusif t’attend dès 75€ d’achat en boutique. Sélection de soins et parfums du moment, dans la limite des stocks.',
  },
  {
    id: 'mdm',
    brand: 'Maisons du Monde',
    category: 'maison',
    offer: 'Bon d’achat dès 150€',
    teaser: 'Bon d’achat',
    distance: 680, distanceLabel: '680 m', walk: 9,
    why: 'Pour ton intérieur — un style chaleureux que tu aimes.',
    sponsored: false,
    grad: ['#A9794E', '#D8B48A'], ink: '#2B2017',
    wordmark: { text: 'Maisons du Monde', spacing: 1, weight: 500, italic: false, serif: true, size: 22 },
    x: 0.2, y: 0.66,
    address: '10 bd Haussmann, 75009',
    desc: 'Un bon d’achat t’est offert dès 150€ dépensés. Mobilier chaleureux, textiles et décoration pour réchauffer ton intérieur cette saison.',
  },
  {
    id: 'frankie',
    brand: 'The Frankie Shop',
    category: 'mode',
    offer: '-15% sur la collection été',
    teaser: 'Collection été',
    distance: 450, distanceLabel: '450 m', walk: 6,
    why: 'Coupes minimalistes et tons neutres — pile dans tes goûts.',
    sponsored: false,
    grad: ['#C8A06A', '#EADBC2'], ink: '#3A2E1E',
    wordmark: { text: 'THE FRANKIE SHOP', spacing: 2, weight: 500, italic: false, size: 17 },
    x: 0.7, y: 0.55,
    address: '5 rue du Vert-Bois, 75003',
    desc: 'La collection été passe à -15%. Tailoring relâché, mailles et basiques élevés — la silhouette du moment, à prix doux.',
  },
  {
    id: 'boulanger',
    brand: 'Boulanger',
    category: 'tech',
    offer: 'Sony WH-1000XM5 à -20%',
    teaser: 'Casque Sony -20%',
    distance: 1200, distanceLabel: '1,2 km', walk: 15,
    why: 'Tu as repéré du son premium récemment — bon plan juste pour toi.',
    sponsored: false,
    grad: ['#24201C', '#4A4038'], ink: '#F4EEE6',
    wordmark: { text: 'Boulanger', spacing: 1, weight: 600, italic: false, size: 24 },
    x: 0.84, y: 0.78,
    address: 'Forum des Halles, 75001',
    desc: 'Le casque à réduction de bruit Sony WH-1000XM5 à -20%. Son immersif, autonomie longue durée — testable en boutique avant d’acheter.',
  },
  {
    id: 'lbm',
    brand: 'Le Bon Marché',
    category: 'mode',
    offer: 'Offre exclusive en boutique',
    teaser: 'Offre exclusive',
    distance: 300, distanceLabel: '300 m', walk: 4,
    why: 'Le grand magasin que tu adores — une offre rien que pour aujourd’hui.',
    sponsored: true,
    grad: ['#B89B6A', '#E7D6B0'], ink: '#332813',
    wordmark: { text: 'LE BON MARCHÉ', spacing: 3, weight: 500, italic: false, size: 17 },
    x: 0.46, y: 0.62,
    address: '24 rue de Sèvres, 75007',
    desc: 'Une offre exclusive t’attend au Bon Marché Rive Gauche, aujourd’hui seulement. Mode, maison et épicerie fine réunies sous un même toit.',
  },
  {
    id: 'aesop',
    brand: 'Aesop',
    category: 'beaute',
    offer: 'Offre exclusive en boutique',
    teaser: 'Offre exclusive',
    distance: 450, distanceLabel: '450 m', walk: 6,
    why: 'Soins raffinés — exactement ta zone de goût beauté.',
    sponsored: false,
    grad: ['#5E5B3E', '#B7B189'], ink: '#FAF7EC',
    wordmark: { text: 'Aēsop', spacing: 2, weight: 500, italic: false, serif: true, size: 28 },
    x: 0.28, y: 0.5,
    address: '256 rue St-Honoré, 75001',
    desc: 'Une offre exclusive sur la gamme soin. Formules d’origine végétale, rituels visage et corps — conseil personnalisé en boutique.',
  },
  {
    id: 'axel',
    brand: 'Axel Arigato',
    category: 'mode',
    offer: 'Ton cadeau dès 75€ d’achat',
    teaser: 'Cadeau offert',
    distance: 300, distanceLabel: '300 m', walk: 4,
    why: 'Sneakers épurées et streetwear pointu — fait pour ton style.',
    sponsored: false,
    grad: ['#7C756E', '#C4BBB2'], ink: '#211D19',
    wordmark: { text: 'AXEL ARIGATO', spacing: 3, weight: 500, italic: false, size: 18 },
    x: 0.62, y: 0.46,
    address: '12 rue de Marseille, 75010',
    desc: 'Un cadeau offert dès 75€ d’achat. Sneakers minimalistes et pièces streetwear scandinaves — la sélection signature de la maison.',
  },
];

Object.assign(window, { CATEGORIES, OFFERS });
